<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UmbracoVersion Condition="'$(UmbracoVersion)' == ''">18.1.0</UmbracoVersion>
    <UmbracoMajor>$(UmbracoVersion.Split('.')[0])</UmbracoMajor>
    <TargetFramework Condition="'$(UmbracoMajor)' == '16'">net9.0</TargetFramework>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestSite\TestSite.csproj" />
  </ItemGroup>

</Project>