using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Options;

namespace BaryoDev.Umbraco.Pwa.Services;

public interface IPwaAssetGenerator
{
    string Manifest();
    string ServiceWorker();
    string Client();
}

/// <summary>
/// Renders the manifest, the service worker and the client script from configuration.
/// The service worker is a direct port of <c>@baryodev/pwa-kit</c>'s generator, so a site running
/// this package and a site running the npm package get byte-comparable caching behaviour.
/// </summary>
internal class PwaAssetGenerator : IPwaAssetGenerator
{
    private static readonly JsonSerializerOptions Json = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        WriteIndented = true,
    };

    private readonly IOptionsMonitor<PwaOptions> _options;

    public PwaAssetGenerator(IOptionsMonitor<PwaOptions> options) => _options = options;

    public string Manifest()
    {
        var m = _options.CurrentValue.Manifest;
        var name = string.IsNullOrWhiteSpace(m.Name) ? "App" : m.Name!;

        return JsonSerializer.Serialize(new
        {
            name,
            short_name = string.IsNullOrWhiteSpace(m.ShortName) ? name : m.ShortName,
            description = m.Description,
            start_url = m.StartUrl,
            display = m.Display,
            theme_color = m.ThemeColor,
            background_color = m.BackgroundColor,
            icons = m.Icons.Select(i => new
            {
                src = i.Src,
                sizes = i.Sizes,
                type = i.Type,
                purpose = i.Purpose,
            }),
        }, Json);
    }

    public string ServiceWorker()
    {
        var sw = _options.CurrentValue.ServiceWorker;
        var version = string.IsNullOrWhiteSpace(sw.Version)
            ? Assembly.GetExecutingAssembly().GetName().Version?.ToString(3) ?? "v1"
            : sw.Version!;

        var shell = J($"{sw.CachePrefix}-shell-{version}");
        var api = J($"{sw.CachePrefix}-api-{version}");
        var apiPrefix = J(sw.ApiPrefix);
        var skip = JsonSerializer.Serialize(sw.SkipPaths);
        var navFallback = J(sw.NavigationFallback);

        return $$"""
// Generated by BaryoDev.Umbraco.Pwa. Configured under BaryoDev:Pwa, not edited here.
const SHELL = {{shell}};
const API = {{api}};
const API_PREFIX = {{apiPrefix}};
const SKIP = {{skip}};
const NAV_FALLBACK = {{navFallback}};

self.addEventListener("install", () => self.skipWaiting());

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== SHELL && k !== API).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("message", (event) => {
  if (event.data === "clear-api-cache") event.waitUntil(caches.delete(API));
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (SKIP.some((p) => url.pathname.startsWith(p))) return;

  // Live data: fresh when online, cached copy only as an offline fallback.
  if (url.pathname.startsWith(API_PREFIX)) {
    event.respondWith(
      fetch(req)
        .then((resp) => {
          if (resp.ok && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(API).then((c) => c.put(req, copy));
          }
          return resp;
        })
        .catch(() =>
          caches.match(req).then(
            (cached) =>
              cached ||
              new Response(JSON.stringify({ offline: true }), {
                status: 503,
                headers: { "Content-Type": "application/json" },
              }),
          ),
        ),
    );
    return;
  }

  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then((resp) => {
          const copy = resp.clone();
          caches.open(SHELL).then((c) => c.put(req, copy));
          return resp;
        })
        .catch(() => caches.match(req).then((r) => r || caches.match(NAV_FALLBACK))),
    );
    return;
  }

  event.respondWith(
    caches.match(req).then(
      (cached) =>
        cached ||
        fetch(req).then((resp) => {
          if (resp.ok && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(SHELL).then((c) => c.put(req, copy));
          }
          return resp;
        }),
    ),
  );
});
""";
    }

    public string Client()
    {
        var o = _options.CurrentValue;
        var track = o.TrackInstalls ? "true" : "false";

        var prompt = o.InstallPrompt;
        var appName = Coalesce(prompt.AppName, o.Manifest.ShortName, o.Manifest.Name, "this app");
        var accent = Coalesce(prompt.AccentColor, o.Manifest.ThemeColor, "#2563eb");
        var icon = Coalesce(prompt.IconUrl, o.Manifest.Icons.FirstOrDefault()?.Src, "");

        var promptEnabled = prompt.Enabled ? "true" : "false";
        var promptName = J(appName);
        var promptDescription = J(prompt.Description);
        var promptAccent = J(accent);
        var promptIcon = J(icon);
        var hideOn = JsonSerializer.Serialize(prompt.HideOnPaths);

        return $$"""
// Generated by BaryoDev.Umbraco.Pwa. Registers the service worker and reports install status.
// Same report shape as @baryodev/pwa-kit, so either client works against this endpoint.
(function () {
  "use strict";

  var KEY = "bd_pwa_device";
  var TRACK = {{track}};

  var PROMPT = {{promptEnabled}};
  var APP_NAME = {{promptName}};
  var PROMPT_TEXT = {{promptDescription}};
  var ACCENT = {{promptAccent}};
  var ICON = {{promptIcon}};
  var HIDE_ON = {{hideOn}};
  var DISMISS_KEY = "bd_pwa_dismissed";

  function deviceId() {
    try {
      var id = localStorage.getItem(KEY);
      if (!id) {
        id = (crypto && crypto.randomUUID && crypto.randomUUID()) ||
             Math.random().toString(36).slice(2) + Date.now().toString(36);
        localStorage.setItem(KEY, id);
      }
      return id;
    } catch (e) {
      // Storage blocked in private mode. An ephemeral id still lets one report land.
      return "ephemeral-" + Math.random().toString(36).slice(2);
    }
  }

  function displayMode() {
    var modes = ["fullscreen", "standalone", "minimal-ui"];
    for (var i = 0; i < modes.length; i++) {
      if (window.matchMedia && window.matchMedia("(display-mode: " + modes[i] + ")").matches) {
        return modes[i];
      }
    }
    // iOS reports installed home-screen apps here rather than via display-mode.
    if (navigator.standalone) return "standalone";
    return "browser";
  }

  function platform() {
    var ua = navigator.userAgent;
    if (/iPhone|iPad|iPod/.test(ua)) return "ios";
    if (/Android/.test(ua)) return "android";
    if (/Windows/.test(ua)) return "windows";
    if (/Mac OS X|Macintosh/.test(ua)) return "macos";
    if (/Linux/.test(ua)) return "linux";
    return "other";
  }

  function report(forceInstalled) {
    if (!TRACK) return;
    var mode = displayMode();
    var body = {
      deviceId: deviceId(),
      displayMode: forceInstalled && mode === "browser" ? "standalone" : mode,
      platform: platform(),
      installed: forceInstalled || mode !== "browser"
    };
    try {
      // keepalive so the report survives the page being closed right after launch.
      fetch("/umbraco/pwa/api/report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
        keepalive: true
      }).catch(function () {});
    } catch (e) {
      // Telemetry must never break the site it is measuring.
    }
  }

  if ("serviceWorker" in navigator) {
    window.addEventListener("load", function () {
      navigator.serviceWorker.register("/sw.js").catch(function () {});
    });
  }

  report(false);
  window.addEventListener("appinstalled", function () { report(true); });

  // ---- install prompt -------------------------------------------------------
  //
  // Two different problems wearing one banner. On Android, Chrome fires
  // beforeinstallprompt and hides its own UI behind a menu, so we hold the event and give the
  // visitor a real button. On iOS there is no event and no API at all, so the only thing that
  // can be done is to tell them which buttons to press.

  var deferred = null;

  function dismissed() {
    try { return !!localStorage.getItem(DISMISS_KEY); } catch (e) { return false; }
  }

  function dismiss() {
    try { localStorage.setItem(DISMISS_KEY, "1"); } catch (e) {}
    var el = document.getElementById("bd-pwa-install");
    if (el) el.remove();
  }

  function isIos() {
    var ua = navigator.userAgent;
    return /iphone|ipad|ipod/i.test(ua) ||
           (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1);
  }

  function suppressedHere() {
    var path = location.pathname;
    for (var i = 0; i < HIDE_ON.length; i++) {
      if (path.indexOf(HIDE_ON[i]) === 0) return true;
    }
    return false;
  }

  function banner(bodyHtml, withButton) {
    if (document.getElementById("bd-pwa-install")) return;

    var wrap = document.createElement("div");
    wrap.id = "bd-pwa-install";
    wrap.setAttribute("role", "dialog");
    wrap.setAttribute("aria-label", "Install " + APP_NAME);
    wrap.style.cssText = [
      "position:fixed", "left:12px", "right:12px", "bottom:12px", "z-index:2147483000",
      "max-width:480px", "margin:0 auto", "display:flex", "gap:12px", "align-items:center",
      "padding:12px 14px", "border-radius:12px", "background:#fff", "color:#111",
      "box-shadow:0 6px 28px rgba(0,0,0,.18)", "border:1px solid rgba(0,0,0,.08)",
      "font:14px/1.4 system-ui,-apple-system,Segoe UI,Roboto,sans-serif"
    ].join(";");

    if (ICON) {
      var img = document.createElement("img");
      img.src = ICON;
      img.alt = "";
      img.width = 40;
      img.height = 40;
      img.style.cssText = "border-radius:9px;flex:0 0 auto";
      wrap.appendChild(img);
    }

    var text = document.createElement("div");
    text.style.cssText = "flex:1 1 auto;min-width:0";
    // Built from configured values only, never from anything a visitor supplied.
    text.innerHTML = bodyHtml;
    wrap.appendChild(text);

    if (withButton) {
      var install = document.createElement("button");
      install.type = "button";
      install.textContent = "Install";
      install.style.cssText = [
        "flex:0 0 auto", "border:0", "cursor:pointer", "border-radius:8px",
        "padding:9px 14px", "font-weight:600", "font-size:14px",
        "background:" + ACCENT, "color:#fff"
      ].join(";");
      install.addEventListener("click", function () {
        if (!deferred) return;
        deferred.prompt();
        deferred.userChoice.then(function () { deferred = null; dismiss(); });
      });
      wrap.appendChild(install);
    }

    var close = document.createElement("button");
    close.type = "button";
    close.setAttribute("aria-label", "Dismiss");
    close.textContent = "\u00d7";
    close.style.cssText =
      "flex:0 0 auto;border:0;background:none;cursor:pointer;font-size:22px;line-height:1;color:#666;padding:0 4px";
    close.addEventListener("click", dismiss);
    wrap.appendChild(close);

    document.body.appendChild(wrap);
  }

  function escapeHtml(v) {
    return String(v == null ? "" : v).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  function maybePrompt() {
    if (!PROMPT) return;
    if (dismissed()) return;
    if (suppressedHere()) return;
    if (displayMode() !== "browser") return; // already installed

    if (isIos()) {
      banner(
        "<strong>Install " + escapeHtml(APP_NAME) + "</strong><br>" +
        "Tap Share, then <strong>Add to Home Screen</strong>.",
        false
      );
      return;
    }

    // Non-iOS: wait for the browser to say the site qualifies. Showing an Install button that
    // cannot install anything is worse than showing nothing.
    window.addEventListener("beforeinstallprompt", function (e) {
      e.preventDefault();
      deferred = e;
      banner(
        "<strong>Install " + escapeHtml(APP_NAME) + "</strong><br>" + escapeHtml(PROMPT_TEXT),
        true
      );
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", maybePrompt);
  } else {
    maybePrompt();
  }
})();
""";
    }

    private static string J(string value) => JsonSerializer.Serialize(value);

    private static string Coalesce(params string?[] candidates) =>
        candidates.FirstOrDefault(c => !string.IsNullOrWhiteSpace(c)) ?? string.Empty;
}
