using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Options;

namespace BaryoDev.Umbraco.Pwa.Services;

public interface IPwaAssetGenerator
{
    string Manifest();
    string ServiceWorker();
    string Client();
}

/// <summary>
/// Renders the manifest, the service worker and the client script from configuration.
/// The service worker is a direct port of <c>@baryodev/pwa-kit</c>'s generator, so a site running
/// this package and a site running the npm package get byte-comparable caching behaviour.
/// </summary>
internal class PwaAssetGenerator : IPwaAssetGenerator
{
    private static readonly JsonSerializerOptions Json = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        WriteIndented = true,
    };

    private readonly IOptionsMonitor<PwaOptions> _options;

    public PwaAssetGenerator(IOptionsMonitor<PwaOptions> options) => _options = options;

    public string Manifest()
    {
        var m = _options.CurrentValue.Manifest;
        var name = string.IsNullOrWhiteSpace(m.Name) ? "App" : m.Name!;

        return JsonSerializer.Serialize(new
        {
            name,
            short_name = string.IsNullOrWhiteSpace(m.ShortName) ? name : m.ShortName,
            description = m.Description,
            start_url = m.StartUrl,
            display = m.Display,
            theme_color = m.ThemeColor,
            background_color = m.BackgroundColor,
            icons = m.Icons.Select(i => new
            {
                src = i.Src,
                sizes = i.Sizes,
                type = i.Type,
                purpose = i.Purpose,
            }),
        }, Json);
    }

    public string ServiceWorker()
    {
        var sw = _options.CurrentValue.ServiceWorker;
        var version = string.IsNullOrWhiteSpace(sw.Version)
            ? Assembly.GetExecutingAssembly().GetName().Version?.ToString(3) ?? "v1"
            : sw.Version!;

        var shell = J($"{sw.CachePrefix}-shell-{version}");
        var api = J($"{sw.CachePrefix}-api-{version}");
        var apiPrefix = J(sw.ApiPrefix);
        var skip = JsonSerializer.Serialize(sw.SkipPaths);
        var navFallback = J(sw.NavigationFallback);

        return $$"""
// Generated by BaryoDev.Umbraco.Pwa. Configured under BaryoDev:Pwa, not edited here.
const SHELL = {{shell}};
const API = {{api}};
const API_PREFIX = {{apiPrefix}};
const SKIP = {{skip}};
const NAV_FALLBACK = {{navFallback}};

self.addEventListener("install", () => self.skipWaiting());

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== SHELL && k !== API).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("message", (event) => {
  if (event.data === "clear-api-cache") event.waitUntil(caches.delete(API));
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (SKIP.some((p) => url.pathname.startsWith(p))) return;

  // Live data: fresh when online, cached copy only as an offline fallback.
  if (url.pathname.startsWith(API_PREFIX)) {
    event.respondWith(
      fetch(req)
        .then((resp) => {
          if (resp.ok && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(API).then((c) => c.put(req, copy));
          }
          return resp;
        })
        .catch(() =>
          caches.match(req).then(
            (cached) =>
              cached ||
              new Response(JSON.stringify({ offline: true }), {
                status: 503,
                headers: { "Content-Type": "application/json" },
              }),
          ),
        ),
    );
    return;
  }

  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then((resp) => {
          const copy = resp.clone();
          caches.open(SHELL).then((c) => c.put(req, copy));
          return resp;
        })
        .catch(() => caches.match(req).then((r) => r || caches.match(NAV_FALLBACK))),
    );
    return;
  }

  event.respondWith(
    caches.match(req).then(
      (cached) =>
        cached ||
        fetch(req).then((resp) => {
          if (resp.ok && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(SHELL).then((c) => c.put(req, copy));
          }
          return resp;
        }),
    ),
  );
});
""";
    }

    public string Client()
    {
        var track = _options.CurrentValue.TrackInstalls ? "true" : "false";

        return $$"""
// Generated by BaryoDev.Umbraco.Pwa. Registers the service worker and reports install status.
// Same report shape as @baryodev/pwa-kit, so either client works against this endpoint.
(function () {
  "use strict";

  var KEY = "bd_pwa_device";
  var TRACK = {{track}};

  function deviceId() {
    try {
      var id = localStorage.getItem(KEY);
      if (!id) {
        id = (crypto && crypto.randomUUID && crypto.randomUUID()) ||
             Math.random().toString(36).slice(2) + Date.now().toString(36);
        localStorage.setItem(KEY, id);
      }
      return id;
    } catch (e) {
      // Storage blocked in private mode. An ephemeral id still lets one report land.
      return "ephemeral-" + Math.random().toString(36).slice(2);
    }
  }

  function displayMode() {
    var modes = ["fullscreen", "standalone", "minimal-ui"];
    for (var i = 0; i < modes.length; i++) {
      if (window.matchMedia && window.matchMedia("(display-mode: " + modes[i] + ")").matches) {
        return modes[i];
      }
    }
    // iOS reports installed home-screen apps here rather than via display-mode.
    if (navigator.standalone) return "standalone";
    return "browser";
  }

  function platform() {
    var ua = navigator.userAgent;
    if (/iPhone|iPad|iPod/.test(ua)) return "ios";
    if (/Android/.test(ua)) return "android";
    if (/Windows/.test(ua)) return "windows";
    if (/Mac OS X|Macintosh/.test(ua)) return "macos";
    if (/Linux/.test(ua)) return "linux";
    return "other";
  }

  function report(forceInstalled) {
    if (!TRACK) return;
    var mode = displayMode();
    var body = {
      deviceId: deviceId(),
      displayMode: forceInstalled && mode === "browser" ? "standalone" : mode,
      platform: platform(),
      installed: forceInstalled || mode !== "browser"
    };
    try {
      // keepalive so the report survives the page being closed right after launch.
      fetch("/umbraco/pwa/api/report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
        keepalive: true
      }).catch(function () {});
    } catch (e) {
      // Telemetry must never break the site it is measuring.
    }
  }

  if ("serviceWorker" in navigator) {
    window.addEventListener("load", function () {
      navigator.serviceWorker.register("/sw.js").catch(function () {});
    });
  }

  report(false);
  window.addEventListener("appinstalled", function () { report(true); });
})();
""";
    }

    private static string J(string value) => JsonSerializer.Serialize(value);
}
