<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="PublicApiGenerator" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/BaryoDev.Umbraco.Pwa/BaryoDev.Umbraco.Pwa.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="approved-api/*.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
